In [4]:
#importando libs utilizadas no tutorial
import pandas as pd

#chamando o dataset
df = pd.read_csv('nba_draft_2015.csv')

#testando dataset
df.head()

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767,0.228800
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500,0.229967
3,Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533,0.295850
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583,0.409100

In [5]:
#loc com Ã­ndice
df.loc[[5]]

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
5,Dakari Johnson,C,dakari-johnson,2015,0.491787,0.021341,0.367544,0.417572,0.193544

In [6]:
#loc com array
df.loc[[0,1,2]]

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767,0.228800
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500,0.229967

In [7]:
df.loc[4:8]

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583,0.409100
5,Dakari Johnson,C,dakari-johnson,2015,0.491787,0.021341,0.367544,0.417572,0.193544
6,Devin Booker,SG,3-devin-booker,2015,0.472577,0.073367,0.324467,0.390167,0.212000
7,Willie Cauley-Stein,C,willie-cauley-stein,2015,0.351171,0.047114,0.405990,0.243186,0.303710
8,Rondae Hollis-Jefferson,SF,rondae-hollis-jefferson,2015,0.311909,0.014590,0.368533,0.392481,0.224396

In [8]:
#setando um index para podermos trabalhar com o nome das linhas
df2 = df.set_index('Player')

#testando a alteraÃ§Ã£o
df2.head()

,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
Player,,,,,,,,
Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767,0.228800
Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500,0.229967
Jahlil Okafor,C,jahlil-okafor,2015,0.521661,0.058717,0.409900,0.235533,0.295850
D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583,0.409100

In [9]:
#agora podemos chamar pelo Ã­ndice com nome, por exemplo:
df2.loc['Justise Winslow']

Position                      SF
ID               justise-winslow
Draft Year                  2015
Projected SPM           0.875329
Superstar              0.0835286
Starter                 0.510905
Role Player             0.176767
Bust                      0.2288
Name: Justise Winslow, dtype: object

In [10]:
#selecionar apenas as colunas que queremos tambÃ©m Ã© possivel, neste exemplo um array com as linhas e outro de colunas
df2.loc[['Karl-Anthony Towns', 'Stanley Johnson', 'D`Angelo Russell'], ['Position', 'ID']]

                   Position                  ID
Player
Karl-Anthony Towns        C  karl-anthony-towns
Stanley Johnson          SF     stanley-johnson
D`Angelo Russell         PG    d-angelo-russell

In [11]:
'''
    Estamos localizando os atletas com probabilidade maior ou igual a 10% de serem superstars
    obs: estou multiplicando por 100, para ficar mais facil o entendimento
'''
df.loc[(df['Superstar']*100) >= 10]

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
4,D`Angelo Russell,PG,d-angelo-russell,2015,0.511967,0.152033,0.342283,0.096583,0.409100
77,Joel Embiid,C,joel-embiid,2014,1.164983,0.147867,0.398188,0.234645,0.219300
78,Marcus Smart,PG,marcus-smart,2014,0.997263,0.163508,0.363846,0.142132,0.330515
81,Andrew Wiggins,SG,andrew-wiggins,2014,0.694105,0.110217,0.422250,0.118000,0.349533
158,Victor Oladipo,SG,victor-oladipo,2013,1.211980,0.160260,0.429232,0.174529,0.235978
159,Nerlens Noel,C,nerlens-noel,2013,1.084449,0.117252,0.479164,0.129400,0.274183
160,Otto Porter,SF,otto-porter,2013,1.032747,0.111765,0.499681,0.127525,0.261029
239,Anthony Davis,PF,3-anthony-davis,2012,1.430365,0.103267,0.589083,0.076133,0.231517
240,Bradley Beal,SG,bradley-beal,2012,1.012450,0.133467,0.491517,0.137333,0.237683
241,Dion Waiters,SG,dion-waiters,2012,0.881299,0.122662,0.403533,0.199038,0.274767
243,Thomas Robinson,PF,thomas-robinson,2012,0.624180,0.114304,0.369210,0.202871,0.313615
324,Derrick Williams,PF,3-derrick-williams,2011,1.156263,0.166002,0.406361,0.159771,0.267865
325,Kyrie Irving,PG,kyrie-irving,2011,0.878822,0.145133,0.384700,0.133517,0.336650
406,DeMarcus Cousins,C,demarcus-cousins,2010,0.462182,0.105282,0.327573,0.217486,0.349658
488,Tyreke Evans,PG,tyreke-evans,2009,1.264907,0.174222,0.460267,0.104356,0.261156
489,Blake Griffin,PF,blake-griffin,2009,0.964880,0.138169,0.371409,0.171448,0.318974
490,James Harden,SG,13-james-harden,2009,0.788386,0.132770,0.404873,0.147432,0.314925
491,Jrue Holiday,PG,jrue-holiday,2009,0.663589,0.102060,0.453846,0.146131,0.297962
568,Michael Beasley,PF,michael-beasley,2008,0.846982,0.146477,0.421324,0.108676,0.323523
569,Russell Westbrook,PG,russell-westbrook,2008,0.772030,0.142845,0.386064,0.169641,0.301449
570,Kevin Love,PF,kevin-love,2008,0.701868,0.124772,0.394285,0.182696,0.298247
571,Eric Gordon,SG,23-eric-gordon,2008,0.571408,0.181979,0.251469,0.190725,0.375826
572,Derrick Rose,PG,derrick-rose,2008,0.370978,0.117010,0.307279,0.160294,0.415417
642,Mike Conley Jr.,PG,mike-conley-jr,2007,1.003193,0.167325,0.404759,0.126162,0.301754
643,Greg Oden,C,greg-oden,2007,0.822608,0.126146,0.382518,0.164270,0.327066
713,Rajon Rondo,PG,rajon-rondo,2006,0.894835,0.122588,0.432486,0.141469,0.303457
714,Tyrus Thomas,PF,tyrus-thomas,2006,0.865401,0.124713,0.412997,0.135411,0.326879
715,LaMarcus Aldridge,PF,lamarcus-aldridge,2006,0.658654,0.101638,0.425575,0.170278,0.302508
790,Chris Paul,PG,chris-paul,2005,1.516427,0.163319,0.489972,0.099133,0.247577
791,Marvin Williams,SF,24-marvin-williams,2005,0.971452,0.109619,0.464429,0.176429,0.249524
847,Andre Iguodala,SG,andre-iguodala,2004,0.723508,0.115663,0.405837,0.160668,0.317832
898,Dwyane Wade,SG,dwyane-wade,2003,0.738702,0.121055,0.369194,0.162433,0.347318
1032,Omar Cook,PG,omar-cook,2001,0.747657,0.150111,0.403133,0.115622,0.331133
1035,Gilbert Arenas,SG,gilbert-arenas,2001,0.433602,0.115286,0.357894,0.181121,0.345700
1037,Joseph Forte,SG,joseph-forte,2001,0.284224,0.123144,0.308617,0.135274,0.432965

In [12]:
#Mudando os 5 primeiros registros para o ano de 2018
df2.loc[0:5, 'Draft Year'] = 2018

df2.head(5)

,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
Player,,,,,,,,
Karl-Anthony Towns,C,karl-anthony-towns,2018,1.030606,0.134767,0.427183,0.163083,0.274967
Justise Winslow,SF,justise-winslow,2018,0.875329,0.083529,0.510905,0.176767,0.228800
Stanley Johnson,SF,stanley-johnson,2018,0.679493,0.067800,0.423733,0.278500,0.229967
Jahlil Okafor,C,jahlil-okafor,2018,0.521661,0.058717,0.409900,0.235533,0.295850
D`Angelo Russell,PG,d-angelo-russell,2018,0.511967,0.152033,0.342283,0.096583,0.409100

In [13]:
# Selecionado a primeira linha do dataset
df.iloc[0]

Player           Karl-Anthony Towns
Position                          C
ID               karl-anthony-towns
Draft Year                     2015
Projected SPM               1.03061
Superstar                  0.134767
Starter                    0.427183
Role Player                0.163083
Bust                       0.274967
Name: 0, dtype: object

In [14]:
 # Selecionando a Ãºltima linha
df.iloc[-1]

Player           Calvin Bowman
Position                     C
ID               calvin-bowman
Draft Year                2001
Projected SPM         -1.68467
Superstar                    0
Starter             0.00506819
Role Player           0.168629
Bust                  0.826303
Name: 1089, dtype: object

In [15]:
# Todos os dados da primeira coluna do dataset
df.iloc[:,0]

0            Karl-Anthony Towns
1               Justise Winslow
2               Stanley Johnson
3                 Jahlil Okafor
4              D`Angelo Russell
5                Dakari Johnson
6                  Devin Booker
7           Willie Cauley-Stein
8       Rondae Hollis-Jefferson
9                    Trey Lyles
10                   Sam Dekker
11              Kelly Oubre Jr.
12                   Tyus Jones
13                 Kevon Looney
14                 Myles Turner
15              Cliff Alexander
16               Christian Wood
17               Frank Kaminsky
18           Michael Frazier II
19               Brandon Ashley
20                 Bobby Portis
21              Andrew Harrison
22                Rashad Vaughn
23               Aaron Harrison
24             Montrezl Harrell
25                   Quinn Cook
26                Cameron Payne
27             Chris McCullough
28              Justin Anderson
29                 Terry Rozier
                 ...
1060            Jeff Trepagnier
1061               Jeryl Sasser
1062             Terence Morris
1063           SirValiant Brown
1064             Michael Wright
1065              Maurice Evans
1066                Alvin Jones
1067                Jerry Green
1068              Kenny Gregory
1069              Casey Calvary
1070                Lee Scruggs
1071            Rashad Phillips
1072           Brian Scalabrine
1073                Kirk Haston
1074             Kimani Ffriend
1075               Damone Brown
1076               Darren Kelly
1077              Michael Hicks
1078               Will Solomon
1079                 Monty Mack
1080                Dean Oliver
1081               Sean Lampley
1082                Terry Black
1083             Cookie Belcher
1084             Eric Chenowith
1085              Terrell Lyday
1086            Brandon Wolfram
1087      Ruben Boumtje Boumtje
1088             Greg Stevenson
1089              Calvin Bowman
Name: Player, Length: 1090, dtype: object

In [16]:
 # Do primeiro ao quinto dado da Ãºltima coluna
df.iloc[0:5,-1]

0    0.274967
1    0.228800
2    0.229967
3    0.295850
4    0.409100
Name: Bust, dtype: float64

In [17]:
df.iloc[[0,1,2,3,4,5],-1]

0    0.274967
1    0.228800
2    0.229967
3    0.295850
4    0.409100
5    0.193544
Name: Bust, dtype: float64

In [18]:
# resgatando as primeiras trÃªs linhas do dataset
df.iloc[0:3]

,Player,Position,ID,Draft Year,Projected SPM,Superstar,Starter,Role Player,Bust
0,Karl-Anthony Towns,C,karl-anthony-towns,2015,1.030606,0.134767,0.427183,0.163083,0.274967
1,Justise Winslow,SF,justise-winslow,2015,0.875329,0.083529,0.510905,0.176767,0.228800
2,Stanley Johnson,SF,stanley-johnson,2015,0.679493,0.067800,0.423733,0.278500,0.229967

In [19]:
# todos os dados da segunda e terceira coluna
df.iloc[:, 1:3]

     Position                       ID
0           C       karl-anthony-towns
1          SF          justise-winslow
2          SF          stanley-johnson
3           C            jahlil-okafor
4          PG         d-angelo-russell
5           C           dakari-johnson
6          SG           3-devin-booker
7           C      willie-cauley-stein
8          SF  rondae-hollis-jefferson
9          PF               trey-lyles
10         SF               sam-dekker
11         SF           kelly-oubre-jr
12         PG               tyus-jones
13         PF             kevon-looney
14         PF           2-myles-turner
15         PF          cliff-alexander
16         PF           christian-wood
17          C           frank-kaminsky
18         SG       michael-frazier-ii
19         PF           brandon-ashley
20         PF             bobby-portis
21         PG          andrew-harrison
22         SG            rashad-vaughn
23         SG         3-aaron-harrison
24         PF         montrezl-harrell
25         PG               quinn-cook
26         PG          2-cameron-payne
27         PF         chris-mccullough
28         SF          justin-anderson
29         PG             terry-rozier
...       ...                      ...
1060       SG          jeff-trepagnier
1061       PG             jeryl-sasser
1062       SF           terence-morris
1063       PG         sirvaliant-brown
1064       PF           michael-wright
1065       SG            maurice-evans
1066        C              alvin-jones
1067       SG              jerry-green
1068       SF            kenny-gregory
1069       PF            casey-calvary
1070       SF              lee-scruggs
1071       PG          rashad-phillips
1072       PF         brian-scalabrine
1073       PF              kirk-haston
1074        C           kimani-ffriend
1075       SF             damone-brown
1076       SG             darren-kelly
1077       SG         11-michael-hicks
1078       PG             will-solomon
1079       SG               monty-mack
1080       PG              dean-oliver
1081       SF             sean-lampley
1082       SF              terry-black
1083       PG           cookie-belcher
1084        C           eric-chenowith
1085       SG            terrell-lyday
1086       SF          brandon-wolfram
1087        C    ruben-boumtje-boumtje
1088       SG           greg-stevenson
1089        C            calvin-bowman

[1090 rows x 2 columns]

In [20]:
# 1Âº,3Âº e 5Âº elementos e 6Âª a 9Âª colunas
df.iloc[[0,2,4], 5:8]

   Superstar   Starter  Role Player
0   0.134767  0.427183     0.163083
2   0.067800  0.423733     0.278500
4   0.152033  0.342283     0.096583

In [23]:
print(type(df.iloc[0]))
print(type(df.iloc[0:3]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>